//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPeronalWebSite.Models.VT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonelWebDbEntities : DbContext
    {
        public PersonelWebDbEntities()
            : base("name=PersonelWebDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_AboutMe> Tbl_AboutMe { get; set; }
        public virtual DbSet<Tbl_Contact> Tbl_Contact { get; set; }
        public virtual DbSet<Tbl_Language> Tbl_Language { get; set; }
        public virtual DbSet<Tbl_Navbar> Tbl_Navbar { get; set; }
        public virtual DbSet<Tbl_ProjectDetails> Tbl_ProjectDetails { get; set; }
        public virtual DbSet<Tbl_Projects> Tbl_Projects { get; set; }
        public virtual DbSet<Tbl_Resource> Tbl_Resource { get; set; }
        public virtual DbSet<Tbl_Technologies> Tbl_Technologies { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_Skills> Tbl_Skills { get; set; }
        public virtual DbSet<Tbl_CurrentProject> Tbl_CurrentProject { get; set; }
    }
}
