//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPeronalWebSite.Models.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AboutMe
    {
        public int ID { get; set; }
        public string ImageURL { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public int LanguageID { get; set; }
        public string LinkedlnURL { get; set; }
        public string GithubURL { get; set; }
        public string EmailAdress { get; set; }
        public string PhoneNumber { get; set; }
        public string Adress { get; set; }
        public string Cv { get; set; }
    
        public virtual Tbl_Language Tbl_Language { get; set; }
    }
}
