//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPeronalWebSite.Models.VT
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_User
    {
        public int ID { get; set; }


        [Required(ErrorMessage = "Password  zorunludur.")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Kullanýcý adý zorunludur.")]
        public string UserName { get; set; }
    }
}
