//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPeronalWebSite.Models.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Projects()
        {
            this.Tbl_ProjectDetails = new HashSet<Tbl_ProjectDetails>();
        }
    
        public int ID { get; set; }
        public int LanguageID { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectImg { get; set; }
        public string ProjectDescription { get; set; }
        public string ProjectEntryTitle { get; set; }
        public string ProjectEntryDescription { get; set; }
    
        public virtual Tbl_Language Tbl_Language { get; set; }
        public virtual Tbl_Language Tbl_Language1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ProjectDetails> Tbl_ProjectDetails { get; set; }
    }
}
