//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPeronalWebSite.Models.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Language
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Language()
        {
            this.Tbl_AboutMe = new HashSet<Tbl_AboutMe>();
            this.Tbl_Contact = new HashSet<Tbl_Contact>();
            this.Tbl_Navbar = new HashSet<Tbl_Navbar>();
            this.Tbl_ProjectDetails = new HashSet<Tbl_ProjectDetails>();
            this.Tbl_Projects = new HashSet<Tbl_Projects>();
            this.Tbl_Projects1 = new HashSet<Tbl_Projects>();
            this.Tbl_Resource = new HashSet<Tbl_Resource>();
            this.Tbl_Technologies = new HashSet<Tbl_Technologies>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public string ShortTitle { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AboutMe> Tbl_AboutMe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Contact> Tbl_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Navbar> Tbl_Navbar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ProjectDetails> Tbl_ProjectDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Projects> Tbl_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Projects> Tbl_Projects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Resource> Tbl_Resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Technologies> Tbl_Technologies { get; set; }
    }
}
