//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPeronalWebSite.Models.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Navbar
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public bool IsActive { get; set; }
        public int LanguageID { get; set; }
        public bool Turn { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public string SeoURL { get; set; }
    
        public virtual Tbl_Language Tbl_Language { get; set; }
    }
}
