//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPeronalWebSite.Models.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProjectDetails
    {
        public int ID { get; set; }
        public int LanguageID { get; set; }
        public int ProjectID { get; set; }
        public string ImageURL { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectDescription { get; set; }
        public System.DateTime Date { get; set; }
        public string Tags { get; set; }
    
        public virtual Tbl_Language Tbl_Language { get; set; }
        public virtual Tbl_Projects Tbl_Projects { get; set; }
    }
}
